version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      ytdlp:
        applies-to: version-updates
        patterns:
          - "yt-dlp*"
          - "bgutil-ytdlp*"
      support-dependencies:
        applies-to: version-updates
        patterns:
          - "*"
        exclude-patterns:
          - "yt-dlp*"
          - "bgutil-ytdlp*"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
