version: 2
updates:
  - package-ecosystem: "pip"
    directory: "~/archiver/"
    schedule:
      interval: "weekly"
    groups:
      pip-version-updates:
        applies-to: version-updates
        patterns: ["*"]
      pip-security-updates:
        applies-to: security-updates
        patterns: ["*"]

  - package-ecosystem: "github-actions"
    directory: "~/archiver/"
    schedule:
      interval: "weekly"
    groups:
      actions-version-updates:
        applies-to: version-updates
        patterns: ["*"]
      actions-security-updates:
        applies-to: security-updates
        patterns: ["*"]

  - package-ecosystem: "docker"
    directory: "~/archiver/"
    schedule:
      interval: "weekly"
    groups:
      docker-version-updates:
        applies-to: version-updates
        patterns: ["*"]
      docker-security-updates:
        applies-to: security-updates
        patterns: ["*"]